apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 # number of pods to spawn. In case a pod fails, job will spawn more pods to ensure 3 successful completions
  parallelism: 3 # optional
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ["expr", "3", "+", "2"]
      restartPolicy: Never