apiVersion: v1
kind: Pod
metadata:
  name: kub
spec:
  containers:
    - name: kubtut
      image: kubetut:latest
      imagePullPolicy: IfNotPresent  # Use the local image if available
      # command and args will be default from dockerfile else overridden
      command: ["mvn"]
      args: ["spring-boot:run"]
      ports:
        - containerPort: 8081
#      env:
#        - name: var1
#          value: variable1
#        - name: var1
      #OR
#          valueFrom:
#            - configMapKeyRef:
#              name: app-config
#              key: var1
      envFrom:
        - configMapRef:
            # centrally store env variables
            name: app-config
        - secretRef:
            name: app-secret