apiVersion: v1
kind: Pod
metadata:
  name: kub
spec:
  securityContext:
    runAsUser: 100 # user id for all containers
  containers:
    - name: kubtut
      image: kubetut:latest
      imagePullPolicy: IfNotPresent  # Use the local image if available
      # command and args will be default from dockerfile else overridden
      command: ["mvn"]
      args: ["spring-boot:run"]
      resources:
        requests:
          memory: "1Gi"
          cpu: 1 # 1 CPU ~ 1 AWS vCPU | GCP Code | Azure Core | Hyperthread
        limits:
          memory: "2Gi"
          cpu: 2
      ports:
        - containerPort: 8081
      securityContext:
        runAsUser: 100 # user id for this container, will override the above one
        capabilities:
          add: [ "MAC_ADMIN" ]
      envFrom:
        - configMapRef:
            # centrally store env variables
            name: app-config
        - secretRef:
            name: app-secret
#  serviceAccountName: dashboard-sa
#  autoMountServiceAccount: false
#      env:
#        - name: var1
#          value: variable1
#        - name: var1
      #OR
#          valueFrom:
#            - configMapKeyRef:
#              name: app-config
#              key: var1
