apiVersion: v1 # one to one mapping with volume claims, so even the volume is not fully used, no other claim can use this
kind: PersistentVolume # central definition of volumes
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    - path: /path