#this is on namespace level, total consumption of resources
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rsq
spec:
  hard:
    requests.cpu: 4
    requests.memory: 4Gi
    limits.cpu: 10
    limits.memory: 10Gi